import Head from "next/head";
import { Header } from "../components";
import Layout from "../components/Layout";
import Main from "../components/main/Main";

export default function Home() {
  return (
    <div className="main_bg">
      <div className="bg-[#191919] min-h-screen 2xl:container mx-auto font-serif">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Layout />
          <Header />
          <Main />
        </div>
      </div>
    </div>
  );
}
